// Builds data/words.js: one entry per word say.js can speak — its full name (for abbreviations), a plain-English
// meaning, and a drug-card link for drugs. Sources: tools/words-src.js, data/glossary.js, data/drugs-*.js and the
// pronunciation list in say.js. Run: node tools/build_words.js
const fs = require('fs'), path = require('path');
const R = path.join(__dirname, '..');
global.window = {};
require(path.join(R, 'data/glossary.js'));
['cardio', 'resp', 'heme'].forEach(f => require(path.join(R, 'data/drugs-' + f + '.js')));
const { ABBR, DEFS } = require('./words-src.js');
const sayAll = fs.readFileSync(path.join(R, 'say.js'), 'utf8');
const say = sayAll.slice(sayAll.indexOf('var WORDS = ['), sayAll.indexOf('];', sayAll.indexOf('var WORDS = [')));
const SAY = [...say.matchAll(/'([^'|]+)\|([^'|]+)(?:\|([^']+))?'/g)].map(m => ({ term: m[1], re: m[2], say: m[3] || '' }));
const have = new Set(SAY.map(s => s.term.toLowerCase()));
const def = {}, add = [];
const put = (t, v) => { const k = t.toLowerCase(); def[k] = Object.assign({}, def[k] || {}, Object.fromEntries(Object.entries(v).filter(([, x]) => x))); };

// Glossary: each name in an entry's heading ("Afterload / preload", "ANC") gets that entry's meaning.
window.GLOSSARY.forEach(([head, , meaning]) => {
  head.split(/\s*\/\s*/).forEach(part => {
    const m = part.match(/^([^(]+?)\s*(?:\(([^)]*)\))?$/); if (!m) return;
    [m[1], m[2]].filter(Boolean).forEach(name => put(name.trim(), { def: meaning }));
  });
});
// Drugs: generic and brand names → class, what it does, what it's for, and its card.
const clean = s => String(s || '').replace(/\s+/g, ' ').trim();
window.DRUG_DATA.drugs.forEach(d => {
  const meaning = clean(d.c) + '. ' + clean(d.plain) + ' Used for: ' + clean(d.ind);
  [d.n, d.g].concat(String(d.b || '').split(/[,;]/)).forEach((nm, i) => {
    nm = clean(String(nm || '').replace(/\(.*?\)/g, '').replace(/^with \w+:\s*/, '')); if (!nm) return;
    nm.split(/\s*\/\s*|;\s*/).forEach(x => { if (x.length > 2) put(x, { def: meaning, drug: d.id, full: i >= 2 ? 'Brand name of ' + d.n.toLowerCase() : '' }); });
  });
});
// Abbreviations: full name and meaning; new ones also join the pronunciation list.
ABBR.forEach(line => {
  const [t, full, meaning, re] = line.split('|');
  put(t, { full, def: meaning });
  if (!have.has(t.toLowerCase())) {
    const letters = t.replace(/₂/g, '2').replace(/₁/g, '1').replace(/₃/g, '3');
    add.push([t, re || letters.split('').filter(c => /[A-Za-z0-9]/.test(c)).join('-').toUpperCase(), (re ? re.replace(/-/g, ' ').toLowerCase() : letters.split('').filter(c => /[A-Za-z0-9]/.test(c)).join(' ').toUpperCase()) + ', ' + full]);
  }
});
// The full name already written into say.js for its abbreviations.
SAY.forEach(s => { if (s.say.indexOf(', ') > 0) put(s.term, { full: s.say.split(', ').slice(1).join(', ') }); });
Object.entries(DEFS).forEach(([t, d]) => put(t, { def: d }));
// Every spoken word should now have a meaning.
const missing = SAY.map(s => s.term).concat(add.map(a => a[0])).filter(t => { const e = def[t.toLowerCase()] || def[t.toLowerCase().replace(/e?s$/, '')]; return !e || !(e.def || e.full); });
const out = '// Generated by tools/build_words.js — edit tools/words-src.js instead.\n// add: extra words for say.js [term, respelling, what to say] · def: lowercase word → { full, def, drug }\nwindow.E2_WORDS = ' + JSON.stringify({ add, def }) + ';\n';
fs.writeFileSync(path.join(R, 'data/words.js'), out);
console.log('words with meanings:', Object.keys(def).length, '| new abbreviations:', add.length, '| spoken words still without a meaning:', missing.length, missing.slice(0, 40).join(', '));
