"""Split the Info page into concept-map topics -> data/info-topics.js.

Each chapter section on the Info page becomes:
  - an Overview topic (exam line, intro, connection map, anatomy & physiology)
  - one topic per topic card (Asthma, COPD, ...)
  - a Nursing process (ADPIE) topic
Run from the repo root: python3 tools/extract_info_topics.py
"""
import json, os, re
from bs4 import BeautifulSoup

SRC = 'Exam 2 Info.dc.html'
OUT = 'data/info-topics.js'
TAGS = ('On exam', 'Foundation', 'Related')

def text(el):
    return re.sub(r'\s+', ' ', el.get_text(' ')).strip()

def strings(el):
    return [s.strip() for s in el.stripped_strings if s.strip()]

def slug(s):
    return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')[:40]

def tidy(s):
    return re.sub(r'\s+([,;:.])', r'\1', s)

def clean(html):
    # Values the Info page's own script filled in; keep blocks fully visible.
    return html.replace('{{ nxOp }}', '1').replace('{{ nxFilter }}', 'none')

def tag_and_title(card):
    ss = strings(card)
    tag = ss[0] if ss and ss[0] in TAGS else ''
    # The title is the first short element (it can contain <b>/<span>, so use the
    # element's whole text rather than its first string).
    for el in card.find_all(True):
        tx = text(el)
        for t in TAGS:
            if tx.startswith(t + ' '):
                tx = tx[len(t) + 1:]
        if 3 <= len(tx) <= 110 and tx not in TAGS and not el.find(lambda e: e.name in ('div', 'p') and len(text(e)) > 110):
            return tag, tx
    rest = [s for s in ss if s not in TAGS]
    return tag, (rest[0] if rest else '')

t = open(SRC, encoding='utf-8').read()
soup = BeautifulSoup(t[t.find('<x-dc>'):t.find('</x-dc>') + 7], 'html.parser')
topics = []
for sec in soup.find_all('section'):
    m = re.match(r'ch(\d+)$', sec.get('id', ''))
    if not m:
        continue
    ch = m.group(1)
    kids = [k for k in sec.find_all(recursive=False) if len(text(k)) > 20]
    h2 = sec.find('h2')
    ch_title = text(h2) if h2 else 'Chapter ' + ch
    overview, cards, adpie = [], [], None
    for k in kids:
        tx = text(k)
        if tx.startswith('Chapter ' + ch + ' check') or tx.startswith(ch + ' check'):
            continue
        if tx.startswith('The nursing process for this chapter'):
            adpie = k
            continue
        subs = [c for c in k.find_all(recursive=False) if len(text(c)) > 600]
        # A group holds two or more large topic cards; a lone card is a topic too.
        if len(tx) > 3000 and not tx.startswith('Down to the anatomy') and not tx.startswith('Connection Map'):
            if len(subs) >= 2 and all(not text(c).startswith('Why ') for c in subs[:2]):
                cards.extend(subs)
            else:
                cards.append(k)
        else:
            overview.append(k)
    exam_line = next((text(k) for k in overview if text(k).startswith('On Exam 2')), '')
    topics.append({'id': ch + '-overview', 'ch': ch, 'chTitle': ch_title, 'title': 'Overview & how it fits together',
                   'kind': 'overview', 'tag': 'On exam' if exam_line else 'Foundation', 'exam': exam_line,
                   'html': clean(''.join(str(k) for k in overview))})
    seen = set()
    for c in cards:
        tag, title = tag_and_title(c)
        title = tidy(title.strip(' —'))
        tid = ch + '-' + slug(title)
        if tid in seen:
            tid += '-2'
        seen.add(tid)
        topics.append({'id': tid, 'ch': ch, 'chTitle': ch_title, 'title': title, 'kind': 'topic', 'tag': tag,
                       'html': clean(str(c))})
    if adpie is not None:
        topics.append({'id': ch + '-adpie', 'ch': ch, 'chTitle': ch_title, 'title': 'Nursing process (ADPIE)',
                       'kind': 'adpie', 'tag': 'Foundation', 'html': clean(str(adpie))})

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('// Generated by tools/extract_info_topics.py from the Info page. Do not edit by hand.\n')
    f.write('window.INFO_TOPICS = ' + json.dumps(topics, ensure_ascii=False) + ';\n')
for tp in topics:
    print(tp['ch'], tp['kind'][:4], (tp['tag'] or '-')[:7].ljust(7), len(tp['html']), tp['title'][:70])

# A light index (no notes) for the practice pages, which only need ids, chapters and titles for focus.js.
with open(os.path.join(os.path.dirname(OUT), 'topic-index.js'), 'w', encoding='utf-8') as f:
    f.write('// Map topics without their notes — enough for focus.js on the practice pages. Rebuilt by tools/extract_info_topics.py.\n')
    f.write('window.INFO_TOPICS = window.INFO_TOPICS || ' + json.dumps([{k: t[k] for k in ('id', 'ch', 'title', 'kind')} for t in topics], ensure_ascii=False, separators=(',', ':')) + ';\n')
