// Source for data/words.js (run: node tools/build_words.js).
// ABBR: 'ABBR|full name|plain meaning|respelling (optional — letters are spelled out by default)'
// DEFS: plain-English meanings for words that are not in the glossary or the drug cards.
module.exports.ABBR = [
  // Vital signs, routes, orders
  'BP|blood pressure|Force of blood on artery walls; written systolic/diastolic.',
  'SBP|systolic blood pressure|The top number: pressure while the heart squeezes.',
  'DBP|diastolic blood pressure|The bottom number: pressure while the heart relaxes and refills.',
  'MAP|mean arterial pressure|Average pressure pushing blood into organs; about 65 or higher keeps them perfused.|map',
  'PP|pulse pressure|Systolic minus diastolic; widens with stiff arteries in aging.',
  'HR|heart rate|Beats per minute; adult normal about 60–100.',
  'RR|respiratory rate|Breaths per minute; adult normal about 12–20.',
  'VS|vital signs|Temperature, pulse, respirations, blood pressure, SpO₂ and pain.',
  'LOC|level of consciousness|How awake and oriented the client is — an early sign of low oxygen or perfusion when it changes.',
  'SOB|shortness of breath|The feeling of not getting enough air (dyspnea).',
  'DOE|dyspnea on exertion|Shortness of breath that comes with activity.',
  'IV|intravenous|Given into a vein.',
  'IM|intramuscular|Injected into a muscle.',
  'SC|subcutaneous|Injected into the fat layer under the skin (also written SubQ).',
  'SubQ|subcutaneous|Injected into the fat layer under the skin.|SUB-Q',
  'PO|by mouth|From Latin per os: the drug is swallowed.',
  'SL|sublingual|Dissolved under the tongue (like nitroglycerin tablets).',
  'NPO|nothing by mouth|No food or drink — for example until the gag reflex returns.',
  'PRN|as needed|Given only when the client needs it, within the order’s limits.',
  'BID|twice a day|From Latin bis in die.',
  'HOB|head of bed|How high the head of the bed is raised (e.g., HOB 30–45° to ease breathing).',
  'ADL|activities of daily living|Bathing, dressing, eating, toileting, moving — what tells you how a client copes day to day.',
  'MAR|medication administration record|The chart where each ordered dose, time and hold parameter is listed and signed.|M-A-R',
  'OTC|over the counter|Sold without a prescription (aspirin, NSAIDs, decongestants, herbals).',
  'NC|nasal cannula|Prongs in the nose delivering oxygen at about 1–6 L/min.',
  'D5W|5% dextrose in water|An IV fluid of sugar water.|D-5-W',
  'KCl|potassium chloride|The usual potassium replacement; never given IV push.',
  'ER|extended release (or emergency room)|On a drug label: releases slowly — swallow whole.',
  'XL|extended length (extended release)|The drug releases over the whole day — do not crush.',
  // Hearts, lungs and blood: anatomy and tests
  'SA|sinoatrial|The SA node is the heart’s natural pacemaker in the right atrium.',
  'AV|atrioventricular|The AV node is the gate that delays the impulse between atria and ventricles.',
  'LV|left ventricle|The main pumping chamber; it sends blood to the body.',
  'RV|right ventricle|Pumps blood to the lungs.',
  'RA|right atrium|Receives blood returning from the body.',
  'LA|left atrium|Receives blood from the lungs.',
  'LAD|left anterior descending artery|The coronary artery feeding the front of the heart — the “widow-maker”.',
  'RCA|right coronary artery|Feeds the right heart and usually the SA and AV nodes.',
  'LCX|left circumflex artery|Coronary artery feeding the side and back of the left ventricle.',
  'SVC|superior vena cava|The large vein returning blood from the head and arms; tumors can block it (SVC syndrome).',
  'SV|stroke volume|Blood pumped out with each beat; set by preload, afterload and contractility.',
  'CO|cardiac output (or carbon monoxide)|Cardiac output = heart rate × stroke volume. In smoke inhalation, CO is carbon monoxide.',
  'CO₂|carbon dioxide|The gas we breathe out; it builds up when breathing is too slow or shallow.|C-O-2',
  'PVR|pulmonary vascular resistance|How hard it is to push blood through the lung vessels; high in pulmonary hypertension.',
  'EF|ejection fraction|Percent of blood the left ventricle pumps out per beat; normal about 55–70%.',
  'PMI|point of maximal impulse|Where the apical pulse is felt best — 5th intercostal space, midclavicular line.',
  'ST|ST segment|The flat part of the ECG after QRS; raised or lowered with heart muscle injury or ischemia.',
  'QT|QT interval|Time for the ventricles to fire and recover; a long QT risks torsades.',
  'QTc|corrected QT interval|The QT adjusted for heart rate.',
  'PR|PR interval|Time from the atria firing to the ventricles firing; normal 0.12–0.20 seconds.',
  'aVR|augmented vector right|One of the six limb leads of the 12-lead ECG.|A-V-R',
  'aVL|augmented vector left|One of the six limb leads of the 12-lead ECG.|A-V-L',
  'aVF|augmented vector foot|One of the six limb leads of the 12-lead ECG.|A-V-F',
  'PVC|premature ventricular contraction|An early, wide, odd-looking beat from the ventricles.',
  'PAC|premature atrial contraction|An early beat from the atria with a normal-looking QRS.',
  'LBBB|left bundle branch block|A delay in the left bundle branch that widens the QRS.',
  'CPR|cardiopulmonary resuscitation|Chest compressions and breaths for someone without a pulse.',
  'ACLS|Advanced Cardiac Life Support|The code algorithms: shocks, epinephrine, amiodarone and so on.',
  'CRT|cardiac resynchronization therapy (or capillary refill time)|A pacemaker that makes both ventricles squeeze together in heart failure.',
  'VAD|ventricular assist device|A pump that takes over part of the heart’s work.|V-A-D',
  'TEE|transesophageal echocardiogram|An ultrasound of the heart taken from inside the esophagus; NPO before, check gag after.',
  'MUGA|multigated acquisition scan|A nuclear scan that measures ejection fraction.|MOO-gah',
  'CTA|CT angiography|A CT scan with contrast to see blood vessels (e.g., for PE).',
  'CT|computed tomography|A cross-sectional x-ray scan.',
  'MRI|magnetic resonance imaging|A scan using a magnet — screen for metal and pacemakers.',
  'PET|positron emission tomography|A scan showing active tissue, used to stage cancer.|pet',
  'CXR|chest x-ray|Plain chest film.',
  'HRCT|high-resolution CT|A detailed lung CT used for fibrosis.',
  'EEG|electroencephalogram|Records brain waves (used in sleep studies).',
  'EMG|electromyogram|Records muscle activity (used in sleep studies).',
  'EOM|extraocular movements|Eye movements (tracked in sleep studies).',
  'NYHA|New York Heart Association|Heart-failure classes I–IV, by how much activity causes symptoms.',
  'CAD|coronary artery disease|Plaque narrowing the heart’s own arteries.',
  'CHF|congestive heart failure|The heart can’t pump enough, so fluid backs up.',
  'PCI|percutaneous coronary intervention|Opening a coronary artery with a balloon and stent through a catheter.',
  'TIA|transient ischemic attack|A “mini-stroke” whose symptoms clear — a warning sign.',
  'LAA|left atrial appendage|A pouch of the left atrium where clots form in AF.',
  'PAP|pulmonary artery pressure|Pressure in the lung artery; high in pulmonary hypertension.',
  'PAOP|pulmonary artery occlusion pressure|A catheter reading that reflects left-heart filling pressure.',
  'TAA|thoracic aortic aneurysm|A bulge in the aorta inside the chest.',
  'PVD|peripheral vascular disease|Disease of the arteries or veins of the limbs.',
  'TBPI|toe-brachial pressure index|Like the ABI but at the toe, for stiff ankle arteries in diabetes.',
  'SCD|sickle cell disease (or sequential compression device)|In hematology: sickle cell disease. In DVT prevention: inflatable leg sleeves.',
  'GOLD|Global Initiative for Chronic Obstructive Lung Disease|The guideline that stages COPD and guides its inhalers.|gold',
  'GINA|Global Initiative for Asthma|The guideline that steps asthma treatment up and down.|JEE-nah',
  'AHA|American Heart Association|Sets BP categories and heart guidelines.',
  'ACC|American College of Cardiology|Writes heart guidelines with the AHA.',
  'JNC|Joint National Committee|An older U.S. blood-pressure guideline.',
  'DASH|Dietary Approaches to Stop Hypertension|A diet rich in fruit, vegetables and low-fat dairy, low in salt.|dash',
  'MAWDS|Medications, Activity, Weight, Diet, Symptoms|A heart-failure self-care checklist.|mawds',
  'PQRSTU|Provokes, Quality, Radiates, Severity, Time, Understanding|A way to assess pain or a symptom.',
  // Lungs
  'ABG|arterial blood gas|Blood from an artery measuring pH, PaO₂, PaCO₂ and bicarbonate.',
  'PFT|pulmonary function tests|Breathing tests (spirometry) that show obstructive or restrictive disease.',
  'FVC|forced vital capacity|Total air you can blow out after a full breath.',
  'FEV1|forced expiratory volume in 1 second|Air blown out in the first second; low in COPD and asthma.|F-E-V-1',
  'FRC|functional residual capacity|Air left in the lungs after a normal breath out.',
  'TLC|total lung capacity|All the air the lungs hold after a full breath.',
  'DLCO|diffusing capacity for carbon monoxide|How well gas crosses the alveolar wall; low in emphysema and fibrosis.',
  'FiO₂|fraction of inspired oxygen|The percent oxygen being breathed; room air is 21%.|F-I-O-2',
  'SaO₂|arterial oxygen saturation|Oxygen saturation measured in arterial blood.|S-A-O-2',
  'COHb|carboxyhemoglobin|Hemoglobin carrying carbon monoxide instead of oxygen.|C-O-H-B',
  'ETCO|end-tidal CO₂|CO₂ at the end of each breath out (capnography).|end-TY-dal C-O',
  'MDI|metered-dose inhaler|A pressurized inhaler that sprays a measured dose; best with a spacer.',
  'DPI|dry powder inhaler|An inhaler you breathe in from quickly and deeply (Diskus, HandiHaler).',
  'SMI|soft mist inhaler|An inhaler that releases a slow mist (Respimat).',
  'HFA|hydrofluoroalkane|The propellant in modern metered-dose inhalers.',
  'BiPAP|bilevel positive airway pressure|Mask ventilation with a higher pressure in and lower pressure out.|BYE-pap',
  'NIV|noninvasive ventilation|Breathing support by mask (CPAP/BiPAP) instead of a breathing tube.',
  'NPPV|noninvasive positive-pressure ventilation|Mask ventilation such as BiPAP.',
  'HFCWO|high-frequency chest wall oscillation|A vibrating vest that loosens mucus in cystic fibrosis.',
  'ARDS|acute respiratory distress syndrome|Severe lung injury: leaky alveoli fill with fluid and oxygen falls despite oxygen.',
  'CF|cystic fibrosis|A genetic disease making thick mucus in the lungs and pancreas.',
  'CFTR|cystic fibrosis transmembrane conductance regulator|The chloride channel that is faulty in cystic fibrosis.',
  'CAP|community-acquired pneumonia|Pneumonia caught outside the hospital.|cap',
  'HAP|hospital-acquired pneumonia|Pneumonia starting 48 hours or more after admission.|hap',
  'VAP|ventilator-associated pneumonia|Pneumonia in a client on a breathing machine.|vap',
  'HCAP|health care–associated pneumonia|An older label for pneumonia linked to health-care contact.|AITCH-cap',
  'DRSP|drug-resistant Streptococcus pneumoniae|Pneumococcus that resists common antibiotics.',
  'RSV|respiratory syncytial virus|A common respiratory virus, severe in infants and older adults.',
  'SARS|severe acute respiratory syndrome|A coronavirus illness; COVID-19 is caused by SARS-CoV-2.|sarz',
  'MERS|Middle East respiratory syndrome|A coronavirus illness spread from camels.|merz',
  'COVID|coronavirus disease|COVID-19, caused by SARS-CoV-2.|KOE-vid',
  'CoV|coronavirus|The virus family behind COVID-19, SARS and MERS.|C-O-V',
  'ACE2|angiotensin-converting enzyme 2|The receptor the COVID virus uses to enter cells.|ace 2',
  'NAAT|nucleic acid amplification test|A PCR-type test that detects a germ’s genetic material.|nat',
  'PCR|polymerase chain reaction|A lab test that copies and detects a germ’s genetic material.',
  'H1N1|influenza A H1N1|The flu strain behind the 2009 pandemic.|H-1-N-1',
  'TST|tuberculin skin test|The Mantoux test: read induration at 48–72 hours.',
  'IGRA|interferon-gamma release assay|A TB blood test, not affected by the BCG vaccine.|IG-rah',
  'BCG|bacille Calmette-Guérin|A TB vaccine used in some countries; can make the skin test positive.',
  'AFB|acid-fast bacilli|The TB stain on sputum smears.',
  'MTB|Mycobacterium tuberculosis|The bacterium that causes TB.',
  'MDR|multidrug-resistant|TB resistant to isoniazid and rifampin.',
  'XDR|extensively drug-resistant|TB resistant to even more drugs than MDR-TB.',
  'AIIR|airborne infection isolation room|A negative-pressure room for TB, measles, chickenpox.',
  'DOT|directly observed therapy|A nurse watches the client swallow each TB dose.',
  'VDOT|video directly observed therapy|DOT done by video.',
  'RIPE|rifampin, isoniazid, pyrazinamide, ethambutol|The four first-line TB drugs.|ripe',
  'INH|isoniazid|A first-line TB drug; give with vitamin B6.',
  'RIF|rifampin|A first-line TB drug; turns fluids orange.|rif',
  'PZA|pyrazinamide|A first-line TB drug; watch uric acid and liver.',
  'MRSA|methicillin-resistant Staphylococcus aureus|A staph germ resistant to many antibiotics.|MER-sah',
  'HIV|human immunodeficiency virus|The virus that causes AIDS; raises TB risk.',
  'AIDS|acquired immunodeficiency syndrome|Advanced HIV infection.|aidz',
  'HPV|human papillomavirus|A virus linked to some head and neck cancers.',
  'EVALI|e-cigarette or vaping use–associated lung injury|Lung injury from vaping.|ee-VAL-ee',
  'THC|tetrahydrocannabinol|The active part of cannabis.',
  'NRT|nicotine replacement therapy|Patches, gum or lozenges that ease nicotine withdrawal.',
  'OSAS|obstructive sleep apnea syndrome|Obstructive sleep apnea with daytime symptoms.',
  'AHI|apnea-hypopnea index|Breathing pauses per hour of sleep; 5 or more means sleep apnea.',
  'UPPP|uvulopalatopharyngoplasty|Surgery removing throat tissue for sleep apnea.',
  'IMF|intermaxillary fixation|Wiring the jaws shut after a fracture — keep wire cutters at the bedside.',
  'SLP|speech-language pathologist|Therapist for swallowing and speech.',
  'SCLC|small cell lung cancer|A fast-growing lung cancer linked to smoking.',
  'NSCLC|non-small cell lung cancer|The most common lung cancer type.',
  'TNM|tumor, node, metastasis|The cancer staging system.',
  'VATS|video-assisted thoracoscopic surgery|Lung surgery through small incisions with a camera.|vats',
  'EGFR|epidermal growth factor receptor|A lung-cancer gene target for some drugs.',
  'ALK|anaplastic lymphoma kinase|A lung-cancer gene target for some drugs.|A-L-K',
  'SIADH|syndrome of inappropriate antidiuretic hormone|Too much ADH → water retention and low sodium (seen with small cell lung cancer).',
  'ACTH|adrenocorticotropic hormone|Pituitary hormone that drives cortisol; some tumors make it.',
  'BMPR2|bone morphogenetic protein receptor 2|A gene linked to inherited pulmonary arterial hypertension.',
  // Blood
  'RBC|red blood cell|Carries oxygen on hemoglobin.',
  'WBC|white blood cell|Fights infection.',
  'Hgb|hemoglobin|The oxygen-carrying protein in red cells; women about 12–16, men about 14–18 g/dL.|H-G-B',
  'Hct|hematocrit|Percent of the blood made of red cells.|H-C-T',
  'MCHC|mean corpuscular hemoglobin concentration|How much hemoglobin is packed in red cells; low = pale (hypochromic).',
  'TIBC|total iron-binding capacity|How much iron the blood could carry; high in iron deficiency.',
  'LDH|lactate dehydrogenase|An enzyme released from broken cells; high in hemolysis and fast-growing cancers.',
  'MMA|methylmalonic acid|Rises in B₁₂ deficiency (not in folate deficiency).',
  'HbS|hemoglobin S|Sickle hemoglobin.|H-B-S',
  'HbF|fetal hemoglobin|Hemoglobin that does not sickle; hydroxyurea raises it.|H-B-F',
  'HbA|adult hemoglobin|Normal adult hemoglobin.|H-B-A',
  'G6PD|glucose-6-phosphate dehydrogenase|An enzyme whose deficiency makes red cells burst with certain drugs or foods.|G-6-P-D',
  'ABO|ABO blood groups|Blood types A, B, AB and O — must match for transfusion.|A-B-O',
  'HLA|human leukocyte antigen|Tissue markers matched for stem cell and organ transplants.',
  'PRBC|packed red blood cells|A red-cell transfusion unit.',
  'PT|prothrombin time|A clotting test (warfarin is followed with the INR from the PT).',
  'PTT|partial thromboplastin time|A clotting test used to follow heparin (often as aPTT).',
  'PF4|platelet factor 4|The platelet protein heparin-induced thrombocytopenia antibodies target.|P-F-4',
  'VITT|vaccine-induced immune thrombotic thrombocytopenia|A rare clotting reaction after some COVID vaccines.|vit',
  'ESA|erythropoiesis-stimulating agent|Drugs like epoetin that make the marrow produce red cells.',
  'ALL|acute lymphoblastic leukemia|The most common childhood leukemia.|A-L-L',
  'AML|acute myeloid leukemia|An acute leukemia of the myeloid line, mostly in adults.',
  'CML|chronic myeloid leukemia|A slow leukemia with the Philadelphia chromosome; treated with tyrosine kinase inhibitors.',
  'CLL|chronic lymphocytic leukemia|A slow leukemia of older adults.',
  'MDS|myelodysplastic syndrome|A marrow disorder making poor blood cells; can turn into leukemia.',
  'HSCT|hematopoietic stem cell transplantation|Replacing the marrow with donor or own stem cells.',
  'TKI|tyrosine kinase inhibitor|A targeted cancer pill (e.g., imatinib for CML).',
  'FCR|fludarabine, cyclophosphamide, rituximab|A chemotherapy combination for CLL.',
  'SOS|sinusoidal obstruction syndrome|Liver vein blockage after stem cell transplant.',
  // Kidney, liver, labs, drugs
  'BUN|blood urea nitrogen|A kidney test; rises with dehydration or kidney injury.',
  'GFR|glomerular filtration rate|How well the kidneys filter; low means drug doses may need lowering.',
  'eGFR|estimated glomerular filtration rate|Kidney filtering estimated from creatinine.|E-G-F-R',
  'CKD|chronic kidney disease|Long-term loss of kidney function; causes anemia (low EPO).',
  'AKI|acute kidney injury|Sudden drop in kidney function (contrast, low perfusion, drugs).',
  'BMP|basic metabolic panel|Sodium, potassium, glucose, BUN, creatinine and more.',
  'LFT|liver function tests|ALT, AST, bilirubin — watched with TB drugs and statins.',
  'ALT|alanine aminotransferase|A liver enzyme; rises with liver injury.',
  'CK|creatine kinase|A muscle enzyme; very high in rhabdomyolysis.',
  'CRP|C-reactive protein|A blood marker of inflammation.',
  'hsCRP|high-sensitivity C-reactive protein|A sensitive inflammation marker used for heart risk.|H-S-C-R-P',
  'HDL|high-density lipoprotein|“Good” cholesterol — carries cholesterol away from arteries.',
  'LDL|low-density lipoprotein|“Bad” cholesterol — deposits in artery walls.',
  'VLDL|very-low-density lipoprotein|A triglyceride-rich cholesterol particle.',
  'TG|triglycerides|Blood fats; target under 150 mg/dL.',
  'A1C|hemoglobin A1C|Average blood sugar over about 3 months.|A-1-C',
  'TSH|thyroid-stimulating hormone|Checked with amiodarone (it can cause thyroid problems).',
  'TFT|thyroid function tests|TSH and thyroid hormones.',
  'BMI|body mass index|Weight for height.',
  'NSAID|nonsteroidal anti-inflammatory drug|Ibuprofen, naproxen — raise bleeding risk and BP.|EN-sed',
  'ACEI|ACE inhibitor|A “-pril” drug that blocks angiotensin II formation.|ace I',
  'CCB|calcium channel blocker|Diltiazem, verapamil, amlodipine.',
  'DHP|dihydropyridine|The amlodipine/nifedipine type of calcium channel blocker — works on vessels.',
  'BB|beta blocker|An “-olol” drug that slows the heart.',
  'MRA|mineralocorticoid receptor antagonist|An aldosterone blocker such as spironolactone.',
  'SGLT2|sodium-glucose cotransporter 2|SGLT2 inhibitors (“-gliflozins”) make the kidney dump sugar and salt; used in heart failure.',
  'SGLT2i|SGLT2 inhibitor|A “-gliflozin” drug used in heart failure and diabetes.',
  'PPI|proton pump inhibitor|An acid-lowering drug (“-prazole”).',
  'PDE3|phosphodiesterase 3|The enzyme cilostazol blocks.|P-D-E-3',
  'PDE4|phosphodiesterase 4|The enzyme roflumilast blocks.|P-D-E-4',
  'CYP3A4|cytochrome P450 3A4|A liver enzyme that clears many drugs; blockers like ritonavir raise their levels.|sip 3-A-4',
  'CYP3A|cytochrome P450 3A|Liver enzymes that clear many drugs.|sip 3-A',
  'HMG|HMG-CoA reductase|The liver enzyme that makes cholesterol; statins block it.',
  'PCSK9|proprotein convertase subtilisin/kexin 9|An enzyme; PCSK9 inhibitor injections lower LDL.|P-C-S-K-9',
  'COX|cyclooxygenase|The enzyme aspirin and NSAIDs block.|cox',
  'TXA₂|thromboxane A₂|A platelet signal that makes platelets clump; aspirin blocks it.|T-X-A-2',
  'ATP|adenosine triphosphate|The cell’s energy currency.',
  'cGMP|cyclic GMP|A signal that relaxes smooth muscle — nitrates and sildenafil both raise it.|cyclic G-M-P',
  'MLCK|myosin light-chain kinase|The switch that makes smooth muscle contract.',
  'MMP|matrix metalloproteinase|Enzymes that break down tissue, including lung elastin.',
  'PAMP|pathogen-associated molecular pattern|Germ markers immune cells recognize.|pamp',
  'TNF|tumor necrosis factor|An inflammatory signal.',
  'AGE|advanced glycation end products|Sugar-damaged proteins that stiffen vessels with aging and diabetes.',
  'VEGF|vascular endothelial growth factor|A signal that grows new blood vessels.|VEJ-eff',
  'mRNA|messenger RNA|Genetic instructions a cell reads to make a protein.|M-R-N-A',
  'DNA|deoxyribonucleic acid|The genetic code.',
  'RNA|ribonucleic acid|Genetic material copied from DNA; some viruses use it.',
  // People and places
  'RN|registered nurse|Assesses, plans, teaches and evaluates — cannot delegate these.',
  'LPN|licensed practical nurse|Gives care and medications to stable clients under RN direction.',
  'UAP|unlicensed assistive personnel|Aides who can do routine care (vitals, hygiene) but not assessment.',
  'AP|assistive personnel (or anterior-posterior)|Delegation: aides. Chest: AP diameter, front-to-back depth.',
  'RT|respiratory therapist|Gives breathing treatments and manages ventilators.',
  'MD|physician|Doctor of medicine.',
  'ED|emergency department|The ER.',
  'ICU|intensive care unit|Unit for critically ill clients.',
  'PACU|post-anesthesia care unit|Recovery room after surgery.|PACK-yoo',
  'EMS|emergency medical services|Ambulance and paramedics (call 911).',
  'RRT|rapid response team|Team you call when a client is deteriorating before a code.',
  'CDC|Centers for Disease Control and Prevention|U.S. public-health agency (isolation, vaccine guidance).',
  'FDA|Food and Drug Administration|U.S. agency that approves drugs and issues boxed warnings.',
  'NCLEX|National Council Licensure Examination|The nursing licensing exam.|EN-klex',
  'NGN|Next Generation NCLEX|The newer case-based NCLEX question types (matrix, bow-tie, cloze…).',
  'ADPIE|assessment, diagnosis, planning, implementation, evaluation|The nursing process.|ad-PIE',
  'GI|gastrointestinal|The stomach and intestines.',
  'CNS|central nervous system|The brain and spinal cord.',
  'CV|cardiovascular|The heart and blood vessels.',
  'UTI|urinary tract infection|Infection of the bladder or kidneys.',
  'GERD|gastroesophageal reflux disease|Stomach acid backing up into the esophagus.|gerd',
  'BPH|benign prostatic hyperplasia|An enlarged prostate — anticholinergics can cause urinary retention.',
  'MODS|multiple organ dysfunction syndrome|Several organs failing, as in severe sepsis.|mods',
  'RUQ|right upper quadrant|Where the liver is — RUQ pain can mean liver injury.',
  'NG|nasogastric|A tube through the nose into the stomach.',
  'MRN|medical record number|A client identifier.',
  'PK|pharmacokinetics|How the body absorbs, spreads, breaks down and removes a drug.',
  'PTFE|polytetrafluoroethylene|Synthetic graft material used in bypass surgery.',
  'AAT|alpha-1 antitrypsin|A protein that protects lung elastin; inherited deficiency causes early emphysema.',
  'RAAS|renin-angiotensin-aldosterone system|The hormone chain that raises BP by squeezing vessels and holding salt and water.|rahz',
  'PDE|phosphodiesterase|Enzymes that break down cAMP/cGMP; blocking them relaxes smooth muscle.',
  'IgE|immunoglobulin E|The allergy antibody; omalizumab blocks it.|I-G-E',
  'IL|interleukin|Immune signaling molecules (IL-4, IL-5, IL-13 drive allergic asthma).',
  'SNS|sympathetic nervous system|“Fight or flight”: raises HR and BP, opens airways.',
  'ADP|adenosine diphosphate|A platelet activator; clopidogrel blocks its receptor (P2Y12).',
  'EPO|erythropoietin|Kidney hormone that tells the marrow to make red cells.',
  'AT₁|angiotensin II type 1 receptor|The receptor ARBs block.|A-T-1',
  'LVH|left ventricular hypertrophy|A thickened left ventricle from pumping against high pressure.',
  'ATPase|adenosine triphosphatase|An enzyme pump that uses ATP (digoxin blocks the Na⁺/K⁺ pump).|A-T-P-ase',
  'P2Y12|platelet ADP receptor|The platelet receptor clopidogrel blocks.|P-2-Y-12',
  'PGE₂|prostaglandin E₂|A prostaglandin that causes fever, pain and inflammation.|P-G-E-2',
  'IP₃|inositol trisphosphate|A signal that releases calcium inside smooth muscle cells.|I-P-3',
  'ENaC|epithelial sodium channel|The kidney sodium channel; amiloride blocks it.|EE-nak',
  'BCR-ABL|BCR-ABL fusion gene|The cancer gene of the Philadelphia chromosome in CML.|B-C-R A-B-L',
  'CSF|cerebrospinal fluid|Fluid around the brain; clear nasal drainage after facial trauma may be CSF.',
  'GVHD|graft-versus-host disease|Donor immune cells attacking the transplant recipient.'
];

module.exports.DEFS = {
  'PaO₂': 'Oxygen dissolved in arterial blood; normal 80–100 mm Hg.',
  VTE: 'Any vein clot: DVT, PE, or both.',
  ACS: 'Unstable angina or a heart attack (STEMI/NSTEMI) — the heart muscle isn’t getting enough blood right now.',
  PAH: 'High pressure in the lung arteries that strains the right heart.',
  IPF: 'Scarring of the lungs with no known cause; stiff lungs, low oxygen.',
  ARB: 'A “-sartan” drug that blocks angiotensin II’s receptor — like an ACE inhibitor without the cough.',
  ARNI: 'Sacubitril/valsartan (Entresto): an ARB plus a drug that keeps natriuretic peptides around longer; used in heart failure.',
  SABA: 'A fast-acting rescue inhaler (albuterol) that opens the airways in minutes.',
  LABA: 'A long-acting airway opener (salmeterol, formoterol) — a controller, never for an attack.',
  LAMA: 'A long-acting anticholinergic inhaler (tiotropium) for COPD maintenance.',
  SAMA: 'A short-acting anticholinergic (ipratropium) that opens airways; often with albuterol.',
  ICS: 'A steroid inhaler (fluticasone, budesonide) that calms airway inflammation over time — a controller, not a rescue. Rinse your mouth after.',
  DOAC: 'Newer oral blood thinners (apixaban, rivaroxaban, dabigatran) — no routine INR checks.',
  LMWH: 'Enoxaparin-type heparin given under the skin; more predictable than IV heparin.',
  EKG: 'Same as ECG — a tracing of the heart’s electrical activity.',
  CBC: 'Complete blood count: red cells, hemoglobin, hematocrit, white cells and platelets.',
  DIC: 'Clotting and bleeding at the same time: tiny clots everywhere use up platelets and clotting factors.',
  ITP: 'The immune system destroys platelets → low platelets and bleeding.',
  TTP: 'Small clots form in tiny vessels and use up platelets — an emergency.',
  LVAD: 'A pump implanted to help a failing left ventricle push blood out.',
  ICD: 'An implanted device that shocks VT/VF back to a normal rhythm.',
  AAA: 'A ballooned abdominal aorta — never palpate it hard; rupture causes severe back pain and shock.',
  STEMI: 'A heart attack with ST elevation — a fully blocked coronary artery; needs reperfusion fast.',
  NSTEMI: 'A heart attack without ST elevation — troponin rises, the artery is partly blocked.',
  CABG: 'Heart bypass surgery: a vein or artery is grafted around blocked coronary arteries.',
  PPE: 'Gloves, gowns, masks/respirators and eye protection.',
  PCA: 'A pump that lets the client give their own opioid doses within set limits.',
  HF: 'The heart can’t pump enough to meet the body’s needs.',
  HTN: 'High blood pressure (130/80 or higher).',
  magnesium: 'An electrolyte that steadies heart rhythm and relaxes muscle; IV magnesium treats torsades.',
  dornase: 'Dornase alfa (Pulmozyme): an inhaled enzyme that cuts up DNA in thick CF mucus.',
  amphotericin: 'Amphotericin B: a strong IV antifungal; watch kidneys, potassium and infusion reactions.',
  epoetin: 'Epoetin alfa: a lab-made erythropoietin that makes the marrow produce red cells.',
  Cordarone: 'An older brand name of amiodarone.',
  Toprol: 'Toprol-XL: brand of metoprolol succinate, the once-daily extended-release form.',
  Clexane: 'The name used for enoxaparin (Lovenox) outside the U.S.',
  Kcentra: '4-factor prothrombin complex concentrate — rapidly reverses warfarin in serious bleeding.',
  Advair: 'Fluticasone + salmeterol in one inhaler (an ICS + LABA controller).',
  Flonase: 'Fluticasone nasal spray for allergies.',
  Symbicort: 'Budesonide + formoterol in one inhaler (an ICS + LABA).',
  Medrol: 'Brand of methylprednisolone tablets (the Medrol Dosepak tapers over 6 days).',
  Trikafta: 'Elexacaftor/tezacaftor/ivacaftor: a CFTR modulator combination for cystic fibrosis.',
  Viagra: 'Sildenafil for erectile dysfunction; never with nitrates.',
  Veletri: 'A brand of IV epoprostenol for pulmonary arterial hypertension.',
  Retacrit: 'A biosimilar of epoetin alfa.',
  Aranesp: 'Brand of darbepoetin, a longer-acting epoetin.',
  Neulasta: 'Brand of pegfilgrastim — one dose per chemo cycle to raise neutrophils.',
  Hydrea: 'Brand of hydroxyurea used for cancers.',
  Narcan: 'Brand of naloxone — reverses opioid overdose.',
  nicotinic: 'Nicotinic receptors respond to acetylcholine and to nicotine.',
  vagus: 'The vagus nerve — the main “rest and digest” nerve; slows the heart and narrows airways.',
  vagal: 'Of the vagus nerve (a vagal response slows the heart).',
  antitrypsin: 'Alpha-1 antitrypsin: protects lung elastin from enzymes; deficiency causes early emphysema.',
  pneumocyte: 'A cell lining the alveoli; type II pneumocytes make surfactant.',
  Henle: 'The loop of Henle in the kidney — where loop diuretics like furosemide work.',
  acidosis: 'Blood too acidic (pH below 7.35).',
  Mantoux: 'The tuberculin skin test — a small injection under the skin, read at 48–72 hours.',
  Wenckebach: 'Second-degree AV block type I: the PR gets longer and longer until a beat drops.',
  Mobitz: 'Mobitz I = Wenckebach (PR lengthens); Mobitz II = PR constant, beats drop suddenly (more dangerous).',
  Trendelenburg: 'Head down, feet up position (not used for shock any more).',
  Fowler: 'Fowler’s position: sitting up in bed (high Fowler’s about 90°) to ease breathing.',
  Virchow: 'Virchow’s triad: slow flow, vessel injury and easy clotting — the three causes of DVT.',
  Kussmaul: 'Kussmaul breathing: deep, fast breaths to blow off acid (as in diabetic ketoacidosis).',
  valsartan: 'An ARB (angiotensin receptor blocker); the second drug in Entresto.',
  rivaroxaban: 'A DOAC — blocks factor Xa; no routine INR. Brand Xarelto.',
  dabigatran: 'A DOAC that blocks thrombin directly; reversed by idarucizumab.',
  tenecteplase: 'A clot-buster like alteplase, given as a single IV push for stroke or MI.',
  simvastatin: 'A statin taken in the evening; lowers LDL.',
  salbutamol: 'The name used outside the U.S. for albuterol.',
  formoterol: 'A long-acting beta₂ agonist (LABA) inhaler; in Symbicort.',
  budesonide: 'An inhaled corticosteroid; in Symbicort.',
  methylprednisolone: 'A corticosteroid given IV (Solu-Medrol) or by mouth (Medrol) for severe asthma and COPD flares.',
  aminophylline: 'The IV form of theophylline.',
  elexacaftor: 'A CFTR corrector; part of Trikafta.',
  tezacaftor: 'A CFTR corrector; part of Trikafta.',
  pirfenidone: 'An antifibrotic for idiopathic pulmonary fibrosis; causes sun sensitivity.',
  rifampicin: 'The name used outside the U.S. for rifampin.',
  pyridoxine: 'Vitamin B₆ — given with isoniazid to prevent nerve damage.',
  ritonavir: 'A booster that blocks liver enzymes (CYP3A) so nirmatrelvir lasts longer — causes many interactions.',
  deferoxamine: 'Binds extra iron; used for iron overdose or iron overload.',
  hydroxocobalamin: 'A form of vitamin B₁₂; also the cyanide antidote.',
  folate: 'Vitamin B₉; needed to make DNA in new blood cells.',
  darbepoetin: 'A longer-acting version of epoetin (Aranesp).',
  pegfilgrastim: 'A once-per-chemo-cycle filgrastim (Neulasta).',
  propranolol: 'A nonselective beta blocker — also blocks β₂, so it can tighten airways.',
  carvedilol: 'A beta blocker that also blocks α₁; used in heart failure.',
  verapamil: 'A heart-slowing calcium channel blocker; causes constipation.',
  nifedipine: 'A vessel-relaxing calcium channel blocker (like amlodipine).',
  idarucizumab: 'The reversal agent for dabigatran (Praxbind).',
  andexanet: 'Reversal agent for apixaban and rivaroxaban (Andexxa).',
  lidocaine: 'A local anesthetic; also an older drug for ventricular dysrhythmias.',
  isosorbide: 'A long-acting nitrate (isosorbide mononitrate/dinitrate) for angina and heart failure.',
  enalapril: 'An ACE inhibitor (like lisinopril).',
  bumetanide: 'A loop diuretic like furosemide but stronger per mg.',
  metformin: 'A diabetes pill; held before and after IV contrast because of kidney risk.',
  glucagon: 'A hormone that raises blood sugar; also the rescue for beta-blocker overdose.',
  flumazenil: 'The reversal agent for benzodiazepines.',
  varenicline: 'A quit-smoking pill (Chantix) that partly stimulates nicotine receptors.',
  bupropion: 'An antidepressant also used to quit smoking (Zyban); lowers the seizure threshold.',
  meperidine: 'An opioid; sometimes used to stop shaking chills (rigors) during amphotericin.',
  diphenhydramine: 'An antihistamine (Benadryl); used to premedicate before infusions.',
  acetaminophen: 'Pain and fever reliever (Tylenol); does not affect platelets.',
  ibuprofen: 'An NSAID; raises bleeding risk and blood pressure.',
  loratadine: 'A non-drowsy antihistamine; eases filgrastim bone pain.',
  loperamide: 'An anti-diarrhea drug; used for nintedanib diarrhea.',
  ondansetron: 'An anti-nausea drug (Zofran); can lengthen the QT.',
  thiamine: 'Vitamin B₁; given in alcohol use disorder.',
  levothyroxine: 'Thyroid hormone replacement.',
  muscarinic: 'The acetylcholine receptors of the “rest and digest” system (slow the heart, narrow airways).',
  parasympathetic: 'The “rest and digest” nervous system, mostly through the vagus nerve.',
  bronchodilator: 'A drug that opens the airways (albuterol, ipratropium).',
  angiotensin: 'A hormone; angiotensin II squeezes blood vessels and triggers aldosterone.',
  natriuretic: 'Making the kidneys get rid of sodium (and water).',
  leukotriene: 'An inflammatory chemical that tightens airways; montelukast blocks it.',
  prostaglandin: 'A local chemical messenger for pain, fever, inflammation and stomach protection.',
  cytokine: 'A signaling protein immune cells use to talk to each other.',
  interleukin: 'A family of cytokines (immune signals).',
  mucociliary: 'Mucus plus cilia — the airway’s cleaning escalator.',
  epithelial: 'Of the epithelium — the lining layer of skin, airways and vessels.',
  alveolus: 'One tiny air sac where oxygen and CO₂ are exchanged.',
  alveolar: 'Of the alveoli (air sacs).',
  oximetry: 'Measuring oxygen saturation with light (pulse oximetry).',
  chemoreceptor: 'A sensor that detects O₂, CO₂ and pH and adjusts breathing.',
  baroreceptor: 'A pressure sensor in the carotid and aorta that adjusts HR and BP.',
  arteriosclerosis: 'Hardening and thickening of artery walls.',
  thromboxane: 'A platelet signal that makes platelets clump and vessels tighten; aspirin blocks it.',
  coagulation: 'The clotting process.',
  hematocrit: 'Percent of the blood made of red cells.',
  parietal: 'Parietal cells in the stomach make acid and intrinsic factor (needed to absorb B₁₂).',
  megaloblastic: 'Large, immature red cells — from B₁₂ or folate deficiency.',
  hypochromic: 'Pale red cells with little hemoglobin — iron deficiency.',
  methylmalonic: 'Methylmalonic acid rises in B₁₂ deficiency.',
  hemolytic: 'Caused by red cells bursting.',
  autosomal: 'Carried on a non-sex chromosome (sickle cell and CF are autosomal recessive).',
  xanthine: 'Xanthine oxidase makes uric acid; allopurinol blocks it in tumor lysis.',
  glucocorticoid: 'A steroid hormone like cortisol; calms inflammation, raises glucose.',
  corticosteroid: 'A steroid drug (prednisone, fluticasone) that calms inflammation.',
  hematopoiesis: 'Blood-cell production in the bone marrow.',
  leukocyte: 'White blood cell.',
  erythrocyte: 'Red blood cell.',
  thrombocyte: 'Platelet.',
  myocardium: 'The heart muscle.',
  pericardium: 'The sac around the heart.',
  mediastinum: 'The middle of the chest between the lungs (heart, great vessels, trachea).',
  pleura: 'The two thin layers lining the lungs and chest wall.',
  pleural: 'Of the pleura (the lining around the lungs).',
  diaphragm: 'The main breathing muscle under the lungs.',
  trachea: 'The windpipe.',
  larynx: 'The voice box.',
  pharynx: 'The throat behind the nose and mouth.',
  epiglottis: 'The flap that covers the airway when you swallow.',
  bronchi: 'The large airways branching from the trachea.',
  bronchiole: 'A small airway leading to the alveoli.',
  mucosa: 'The moist lining of the airways and gut.',
  paroxysmal: 'Coming on suddenly in episodes.',
  bradypnea: 'Slow breathing — under about 12 breaths a minute.',
  hemothorax: 'Blood in the pleural space around the lung.',
  spirometer: 'A device that measures breathing; an incentive spirometer encourages deep breaths.',
  spirometry: 'Breathing tests measuring how much and how fast air moves.',
  apnea: 'A pause in breathing.',
  laryngectomy: 'Removal of the voice box; the client breathes through a neck stoma.',
  asthmaticus: 'As in status asthmaticus: a severe asthma attack that doesn’t respond to usual rescue treatment.',
  tuberculin: 'The purified TB protein injected for the skin test.',
  induration: 'A firm, raised area — what you measure on a TB skin test (not the redness).',
  emphysema: 'COPD with destroyed alveolar walls — air gets trapped.',
  bronchitis: 'Inflamed airways; chronic bronchitis = productive cough for 3+ months in 2 years.',
  'cystic fibrosis': 'Inherited faulty chloride channel → thick, sticky mucus in lungs and pancreas.',
  fibrosis: 'Scarring that stiffens tissue.',
  idiopathic: 'Of unknown cause.',
  pulmonary: 'Of the lungs.',
  peritonsillar: 'Around the tonsil (a peritonsillar abscess can block the airway).',
  trismus: 'Unable to open the mouth fully (jaw spasm).',
  sinusitis: 'Inflamed, infected sinuses.',
  influenza: 'The flu — a contagious respiratory virus.',
  histoplasmosis: 'A fungal lung infection from bird or bat droppings (Ohio/Mississippi valleys).',
  coccidioidomycosis: 'A fungal lung infection from desert soil (“valley fever”).',
  blastomycosis: 'A fungal lung infection from soil near lakes and rivers.',
  anthrax: 'A bacterial infection; inhaled anthrax is deadly but does not spread person to person.',
  hemoptysis: 'Coughing up blood.',
  crepitus: 'Crackling under the skin from trapped air.',
  fremitus: 'Vibration felt on the chest when the client speaks.',
  vesicular: 'Normal soft breath sounds heard over most of the lungs.',
  kyphosis: 'Forward curving of the upper spine (“hunchback”).',
  orthostatic: 'Caused by standing up (orthostatic hypotension = BP drops on standing).',
  diuresis: 'Increased urine output.',
  hyponatremia: 'Low blood sodium (below 135).',
  hypomagnesemia: 'Low blood magnesium — raises the risk of dysrhythmias and digoxin toxicity.',
  myocardial: 'Of the heart muscle.',
  infarction: 'Tissue death from lost blood supply (myocardial infarction = heart attack).',
  fibrillation: 'Chaotic quivering instead of an organized beat.',
  ventricular: 'Of the ventricles (the lower pumping chambers).',
  atrial: 'Of the atria (the upper chambers).',
  defibrillation: 'An unsynchronized shock for pulseless VT or VF.',
  cardioversion: 'A shock timed to the R wave for unstable rhythms that still have a pulse.',
  catheterization: 'Threading a catheter into the heart through an artery to see and open blocked arteries.',
  retroperitoneal: 'Behind the abdominal lining — a hidden place to bleed after femoral catheterization.',
  'vaso-occlusive': 'Blocking blood vessels — sickled cells jamming small vessels causes a pain crisis.',
  lymphoma: 'Cancer of lymphocytes in the lymph nodes.',
  myeloma: 'Cancer of plasma cells in the bone marrow.',
  purpura: 'Purple patches from bleeding under the skin.',
  ecchymosis: 'A bruise.',
  embolism: 'A blockage from something traveling in the blood (usually a clot).',
  embolus: 'A traveling clot or other material that lodges in a vessel.',
  thrombosis: 'A clot forming inside a vessel.',
  thrombus: 'A clot stuck in a vessel.',
  hemostasis: 'Stopping bleeding: platelet plug plus the clotting cascade.',
  neutropenia: 'Low neutrophils — high infection risk (ANC under 1,000–1,500).',
  pancytopenia: 'Low red cells, white cells and platelets all at once.',
  pericarditis: 'Inflamed sac around the heart: sharp chest pain better leaning forward, friction rub.',
  endocarditis: 'Infection of the heart valves or lining.',
  tamponade: 'Fluid in the pericardial sac squeezing the heart — low BP, JVD, muffled heart sounds.',
  cardiomyopathy: 'Disease of the heart muscle itself.',
  aneurysm: 'A ballooned, weakened artery wall.',
  dissection: 'A tear in the inner wall of the aorta letting blood split the layers — tearing pain.',
  hepatotoxicity: 'Liver damage from a drug.',
  ototoxicity: 'Ear damage (hearing loss, ringing) from a drug.',
  nephrotoxicity: 'Kidney damage from a drug.',
  anaphylaxis: 'A severe, life-threatening allergic reaction — epinephrine IM first.',
  angioedema: 'Swelling of the lips, tongue, face or throat — a medical emergency (ACE inhibitors can cause it).',
  rhabdomyolysis: 'Muscle breakdown releasing proteins that can damage the kidneys (rare statin effect).',
  'torsades de pointes': 'A twisting, polymorphic VT linked to a long QT — give IV magnesium.',
  torsades: 'Short for torsades de pointes — a twisting VT linked to a long QT.',
  syncope: 'Fainting.',
  diaphoresis: 'Heavy sweating.',
  diaphoretic: 'Sweating heavily.',
  koilonychia: 'Spoon-shaped nails — a sign of iron deficiency.',
  glossitis: 'A smooth, sore, red tongue — seen in B₁₂ and iron deficiency.',
  pallor: 'Paleness.',
  jaundice: 'Yellow skin and eyes from high bilirubin.',
  paresthesia: 'Numbness or tingling (pins and needles).',
  pica: 'Craving non-food items like ice or clay — a sign of iron deficiency.',
  pernicious: 'Pernicious anemia: B₁₂ deficiency from missing intrinsic factor.',
  aplastic: 'Aplastic anemia: the marrow stops making blood cells.',
  sickle: 'Sickle-shaped red cells that block small vessels.',
  hyperinflation: 'Overinflated lungs from trapped air (COPD, asthma).',
  pleuritic: 'Pain that worsens with breathing in — from irritated pleura.',
  tachydysrhythmia: 'A fast abnormal heart rhythm.',
  dysrhythmia: 'An abnormal heart rhythm.',
  arrhythmia: 'An abnormal heart rhythm (same as dysrhythmia).',
  cardiogenic: 'Caused by the heart (cardiogenic shock = the pump fails).',
  hypovolemia: 'Low blood volume (bleeding, dehydration).',
  hypervolemia: 'Too much fluid volume (heart failure, kidney failure).',
  phlebotomy: 'Drawing blood; removing blood treats polycythemia.',
  transfusion: 'Giving blood products.',
  ischemia: 'Too little blood flow and oxygen to tissue.',
  ischemic: 'Starved of blood flow.',
  necrosis: 'Tissue death.',
  auscultation: 'Listening with a stethoscope.',
  percussion: 'Tapping the chest to hear if it is air-filled, fluid-filled or solid.',
  palpation: 'Feeling with the hands.',
  nebulizer: 'A machine that turns liquid medicine into a mist to breathe in.',
  hemodynamic: 'Relating to blood flow and pressure.',
  inotrope: 'A drug that changes how hard the heart squeezes.',
  inotropic: 'Affecting how hard the heart squeezes (positive inotrope = stronger).',
  chronotropic: 'Affecting heart rate.',
  prophylaxis: 'Prevention.',
  teratogenic: 'Can cause birth defects.',
  neuropathy: 'Nerve damage — numbness, tingling, pain.',
  thrombolytic: 'A clot-dissolving drug (alteplase).',
  fibrinolytic: 'Breaking down fibrin clots (same idea as thrombolytic).',
  antiplatelet: 'A drug that stops platelets clumping (aspirin, clopidogrel).',
  erythropoiesis: 'Red blood cell production.',
  tPA: 'Tissue plasminogen activator (alteplase) — a clot-buster.'
};
